image: Visual Studio 2017

build_script:
- nuget restore -Verbosity quiet
- msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test_script:
- vstest.console /logger:Appveyor test\TippingService.IntegrationTests\bin\Release\TippingService.IntegrationTests.dll
